[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
clap = {version = "4", features = ["derive", "env", "default"] }
libs = {path = "../libs" }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4", "serde"] }


[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.6"