[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = {version = "4", features = ["derive", "env", "default"] }
dotenv = "0.15"
libs = {path = "../libs" }
tokio = { version = "1", features = ["full"] }


[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.6"