name: Pull Request Test

on:
    pull_request:
        branches:
            - main


jobs:
    CI:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3


            - name: Set up rust environment 
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable

            
            - name: Run Code checker (clippy) and Format correction
              run:  |
                cargo clippy
                cargo fmt
            
            - name: Run Test
              run: cargo test -- --test-threads=1

            - name: Compile code with Optimization
              run: cargo build --release