name: Release for Ubuntu

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable

            - name: Compile code for Ubuntu
              run : cargo build --release
            
            - name: Package binary
              run: |
                cd target/release
                tar czf ../../rusty-rolodex-${GITHUB_REF_NAME}-ubuntu-x86_64.tar.gz rusty-rolodex

            - uses: softprops/action-gh-release@v2
              with:
                files: rusty-rolodex-${GITHUB_REF_NAME}-ubuntu-x86_64.tar.gz